services:
  local_postgres:
    image: postgres:16

    container_name: Sales_analytics_wh

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      # Run the master SQL script when PostgreSQL initializes a new volume.
      - ./database:/docker-entrypoint-initdb.d:ro
      # This saves actual row records onto their hard drive so data persists
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4

    container_name: Sales_analytics_pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "${PGADMIN_PORT}:80"

    depends_on:
      - local_postgres

    restart: unless-stopped

volumes:
  postgres_data:
